# Generated by Django 5.2 on 2026-05-17 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('blush', 'Blush'), ('sunshine', 'Sunshine'), ('night', 'Night'), ('pearl', 'Pearl')], default='blush', max_length=20)),
                ('headline', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('photo_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cards.photocard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
